{
    "font_msyhbd_path": "framework_common/manshuo_draw/data/fort/LXGWWenKai-Bold.ttf",
    "font_msyh_path": "framework_common/manshuo_draw/data/fort/LXGWWenKai-Regular.ttf",
    "default_qq_avatar_size": 640
}