bili_dynamic:     #下面的设置暂不可用，请暂时不要修改
  enable: false    #是否开启动态推送功能
  dynamic_interval: 500 #动态检查间隔时间，单位为秒
  并发模式: false #是否启用并发模式，开启后可以同时获取多个动态，但可能会因高频请求导致无法爬取
  screen_shot_mode: "mobile" #mobile为移动端截图，pc为PC端截图
  draw_type: 2    #1代表用playwright（需要安装其余组件）；2代表本地Pillow绘图（有可能出错）
  is_QQ_chek: True #是否检测qq小程序里的视频链接

网易云卡片:    #绘制网易云歌曲分享卡片
  enable: false
  解析自带音频下载url: false #涉及付费音乐版权问题，只能以文件形式发送了,不允许进行传播、销售等商业活动!!
网易云解析:
  enable_proxy: False  #使用common_config/basic_config中填写的代理。
  wyy_prase_url: 'http://nas.manshuo.ink:5000/wyy'      #网易云解析用url，原url已被废弃，请参考https://github.com/Suxiaoqinx/Netease_url
流媒体:
  youtube:
    download_audio_level: 0  #下载音频所需权限等级
    download_video_level: 30  #下载视频所需权限等级
  asmr:
    download_audio_level: 0  #下载音频所需权限等级
