today_wife:
  api:
  - 'https://sese.iw233.top/iapi.php?sort=random'
  - 'https://moe.jitsu.top/api'
  - 'https://api.seaya.link/wap'
  header: 'https://weibo.com/'          #çŸ¥é“çš„è‡ªå·±æ”¹ï¼Œä¸çŸ¥é“çš„ä¸è¦åŠ¨
  wifePrefix: '/'                       #é€ç¾¤å‹çš„æŒ‡ä»¤å‰ç¼€
  ä»Šæ—¥èè‰: True
  ä»Šæ—¥è€å…¬: True
  ä»Šæ—¥è€å©†: True
  å¤è¯»å¼€å…³: True
  ç­¾ğŸ¦Œæ’¤å›: True
  é€ç¾¤å‹æ’¤å›: True
  é€çƒ­é—¨ç¾¤å‹: False #åªä¼šé€åˆ°æœ€è¿‘å‘è¨€è¾ƒå¤šçš„ç¾¤å‹
  is_at: True #ä»Šæ—¥ç¾¤å‹/ç®¡ç†/ç¾¤ä¸» æ˜¯å¦è‰¾ç‰¹å…¶æœ¬äºº