
user_handle_logic: blacklist #æ¨¡å¼ã€‚å¯å¡« blacklist, whitelistã€‚blacklistä¸‹ï¼Œå±è”½æŒ‡å®šç”¨æˆ·ï¼Œwhitelistä¸‹ï¼Œåªå¤„ç†æŒ‡å®šç”¨æˆ·ã€‚
user_handle_logic_operate_level: 1000 #æ‹‰é»‘ã€è§£é»‘ç”¨æˆ·æ‰€éœ€æ“ä½œæƒé™
group_handle_logic: blacklist #æ¨¡å¼ã€‚å¯å¡« blacklist, whitelistã€‚blacklistä¸‹ï¼Œå±è”½æŒ‡å®šç¾¤ï¼Œwhitelistä¸‹ï¼Œåªå¤„ç†æŒ‡å®šç¾¤ã€‚
group_handle_logic_operate_level: 1000 #æ‹‰é»‘ã€è§£é»‘ç¾¤æ‰€éœ€æ“ä½œæƒé™
é‚€è¯·botåŠ ç¾¤æ‰€éœ€æƒé™: 0
ç”³è¯·botå¥½å‹æ‰€éœ€æƒé™: 0
webui:
  enable: true #æ˜¯å¦å¼€å¯web ui
record_mface: true #æ˜¯å¦æ”¶é›†ä¸»äººçš„è¡¨æƒ…åŒ…
proxy:
  http_proxy: ""
  socks_proxy: ""
bot: "Eridanus"   #æœºå™¨äººæ˜µç§°
master:
  name: "ç®¡ç†å‘˜"
  id: 1840094972
group: 879886836   #æµ‹è¯•ç¾¤å·1ï¼Œéšä¾¿å»ºä¸ªå°ç¾¤ã€‚botä¼šå¾€é‡Œé¢å‘ä¹±ä¸ƒå…«ç³Ÿçš„ä¸œè¥¿ï¼Œä¸è¦å¡«ç”¨æˆ·ç¾¤ã€‚
adapter:
  name: "any"   #å…¼å®¹æ€§é€‰é¡¹ï¼Œå¦‚æœç”¨Lagrangeï¼Œåˆ™å¿…é¡»å¡«Lagrangeï¼Œç”¨å…¶ä»–onebotå®ç°åˆ™ä¸ç”¨åŠ¨
  ws_client:   #æœºå™¨äººä½œä¸ºwebsocketå®¢æˆ·ç«¯
    ws_link: "ws://127.0.0.1:3001"  #botçš„websocketè¯·æ±‚åœ°å€


help_menu:
  content:
    page1:
      - { 'type': 'basic_set', 'img_width': 1000,'img_name_save': 'help_menu_page1.png','img_height': 1500,'max_num_of_columns': 3 ,'font_common_size': 34,'font_des_size': 25, 'font_title_size': 46,'spacing': 3,'padding_up': 30}
      - { 'type': 'avatar', 'img': ["https://q1.qlogo.cn/g?b=qq&nk=2319804644&s=640"],'content': ["[name]æ«ä¸å²š[/name]\n[des]å¾ˆé«˜å…´è®¤è¯†ä½ ï½[/des]"],'padding_up_font': 5,'upshift_extra':20 }
      - 'ä½ å¥½ï¼Œè¿™é‡Œ [title]æ«ä¸å²š[/title] å“¦\næˆ‘æ˜¯ä¸€ä¸ªåŸºäº [title]Eridanus[/title] çš„qqæœºå™¨äººï¼Œè¯·å¤šå…³ç…§!!!'
      - {'type': 'text','content': ['  ç°åœ¨ï¼ˆæ•²é»‘æ¿ï¼‰ï¼æ«ä¸å²šä¹Ÿæœ‰å±äºè‡ªå·±çš„äººç‰©å½¢è±¡å•¦ï¼Œå¤§å®¶è¯·çœ‹ï¼'],'layer':2}
      - { 'type': 'img', 'subtype': 'common_with_des','layer':2, 'img': ['https://gal.manshuo.ink/usr/uploads/2025/07/977611811.png','https://gal.manshuo.ink/usr/uploads/2025/07/2873643637.png','https://gal.manshuo.ink/usr/uploads/2025/07/4007464159.png'],'content': ["æ„Ÿè°¢â€™é‚ªæ¶é¥¼å¹²â€˜çš„ç»˜åˆ¶","æ„Ÿè°¢â€™æ¬¢ä¹é˜³å…‰â€˜çš„ç»˜åˆ¶","æ„Ÿè°¢â€™æ«ç³–æ¾é¥¼â€™çš„ç»˜åˆ¶â€˜"] }
      - {'type': 'text','content': ['å¥½è€¶ï¼Œè¿™ä¸‹æ«ä¸å²šä¹Ÿæ˜¯å˜å¾—è¶Šæ¥è¶Šå¯çˆ±äº†å‘¢ï¼ˆå—¯ï¼\né‚£ä¹ˆæ¥ä¸‹æ¥ï¼Œå°±è®©æˆ‘ä»¬ä»‹ç»æ«ä¸å²šçš„å¥‡å¦™èƒ½åŠ›å§ï¼'],'layer':2}
      - '   '
      - { 'type': 'img', 'subtype': 'common_with_des_right','img': [ "https://q1.qlogo.cn/g?b=qq&nk=1270858640&s=640" ],'label': [ 'Bç«™' ],'content': [ ' \nè¿™æ˜¯æˆ‘ä»¬çš„\n                 ---æ¼«æœ”\n \n[des]å…³æ³¨æ¼«æœ”è°¢è°¢å–µå–µ[/des]' ] }
      - {'type': 'text','content': ['[title]æ«ä¸å²šã®åŠŸèƒ½èœå•[/title]\nÂ· ALå¯¹è¯ï¼ˆè‰¾ç‰¹è§¦å‘\nÂ· è½¦é˜Ÿæé†’\n(åˆ›å»ºè½¦é˜Ÿ +é˜Ÿä¼åç§°ã€å‘è½¦ +é˜Ÿä¼åç§°ã€åŠ å…¥ +é˜Ÿä¼åç§°)\nÂ· å¤§é‡å®šæ—¶ä»»åŠ¡æ¨é€\nÂ· Bangumiï¼ˆç•ªå‰§ï¼‰æŸ¥è¯¢\nÂ· GalgameæŸ¥è¯¢/galæ¨è\nÂ· é›€é­‚æŸ¥è¯¢ã€é›€é­‚è®°å½•\nï¼ˆæ”¯æŒä¸‰éº»ä»¥åŠå››éº»æŸ¥è¯¢ï¼Œä»…æœ‰é‡‘ä¹‹é—´ä»¥ä¸Šæ•°æ®ï¼‰'],'layer':2}
      - {'type': 'text','content': ['Â· å¤šå¹³å°é“¾æ¥è§£æ\nï¼ˆBiliBiliã€æŠ–éŸ³ã€å°çº¢ä¹¦ã€å¾®åšã€æ¨ç‰¹ç­‰ï¼‰\nÂ· BiliBiliåŠ¨æ€å®æ—¶æ¨é€\nÂ· PetPetç»˜å›¾ï¼ˆå’•å’•å’•ï¼‰\nÂ· å¥¶é¾™/doroæ£€æµ‹\nÂ· arcaea online\nï¼ˆæš‚ä¸ç»´æŠ¤ï¼ˆå¼ºåˆ¶è¦æ±‚æ‹¥æœ‰arcaea onlineï¼‰\nÂ· é»‘/ç™½åå•ã€æƒé™ç³»ç»Ÿ\n(ç›®å‰æœ‰èº«ä»½ï¼šç®¡ç†å‘˜ã€ä¿¡ä»»è€…ã€è´¡çŒ®è€…ã€ç”¨æˆ·)\nï¼ˆæˆæƒæŒ‡ä»¤ï¼šæˆæƒ + èº«ä»½ï¼‰\nÂ· æ•¬è¯·æœŸå¾…ï¼ˆæ¬¢è¿å‚¬æ›´ï¼Œå’•å’•å’•ï¼'],'layer':2}
      - '   '
      - {'type': 'text','content': ['[title]é™åˆ¶çº§ã®åŠŸèƒ½èœå•[/title]\n[des]æ³¨æ„ï¼šæœ¬åŠŸèƒ½æ¨¡å—å‡ä¸ºé™åˆ¶çº§ï¼Œè¯·ç¾¤å‹è°¨æ…ä½¿ç”¨ï¼Œéƒ¨åˆ†åŠŸèƒ½æœªè·å¾—å¯¹åº”æˆæƒä¸äºˆå¼€æ”¾ï¼Œè¯·è¿›å…¥botç¾¤ï¼ˆ674822468ï¼‰è¯·æ±‚ MASTER æˆæƒ[/des]'],'layer':2}
      - {'type': 'text','content': ['éšæœºasmrï¼ˆR18ï¼‰\nÂ· JMComic ç³»åˆ—ï¼ˆéªŒè½¦ + idã€JMä¸‹è½½ + idã€éšæœºæœ¬å­ç­‰ï¼‰\nÂ· iwaraçƒ­é—¨ï¼ˆåŒ…æ‹¬æœç´¢ç‰¹å®šè§†é¢‘ä¸ä¸‹è½½åŠŸèƒ½ï¼‰'],'layer':2}
      - '   '
      - {'type': 'text','content': ['[title]å°åŠŸèƒ½ã®èœå•[/title]\nÂ· ä»Šæ—¥è€å©†/ç¾¤ä¸»/ç¾¤å‹/å¡”ç½—/è€å…¬/èè‰ç­‰\nÂ· ğŸ¦Œï¼ˆè¿™æ˜¯ä¸€ç§ç”Ÿæ´»ã€ä¸€ç§ç­¾åˆ°æ–¹å¼ï¼‰\nÂ· /é€/å¨¶ç¾¤å‹ç³»åˆ—\nÂ· ç‚¹æ­ŒåŠŸèƒ½ ï¼ˆç‚¹æ­Œ å‘¨æ°ä¼¦ å±‹é¡¶ï¼‰\nÂ· z_libæœä¹¦/ä¸‹è½½\nÂ· æœå›¾ + å›¾ç‰‡\nÂ· å†…ç½®aiç»˜å›¾ï¼ˆæš‚ä¸å¼€æ”¾ï¼‰'],'layer':2}


